# Site
repository: zakdim/zakdim.github.io
favicon: images/favicon.ico

# Personal info
name: Dmitri Zakharov
title: Senior Java Developper
email: dmitri.zakharov@gmail.com 
website: zakdim.github.io

darkmode: true
# Social links

# TODO twitter_username: franck_garcia
github_username:  zakdim
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: dmitri-zakharov-95954a3
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# stack overflow?
additional_links:
        - url: https://stackoverflow.com/users/2800303/dzakharov
          icon: fa-stack-overflow
          title: stackoverflow

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a software developer with progressive experience in architecturing 
  applications with a strong accent on Java ecosystem. Over the years I have
  been building Java/JavaEE solutions for the international freight and
  customs brokerage business. I am passionate about improving myself 
  professionally and learning new skills by following the latest technological
  trends. Over the various mandates I worked on, I broadly extended my skills
  in producing quality solutions. 

  I am most skilled in:     <mark>Java</mark> <mark>Jave EE</mark> <mark>Angular</mark> <mark>Apache Camel</mark> <mark>Spring</mark> <mark>Hibernate</mark> <mark>Docker</mark>

  Currently looking at:     <mark>Kubernetes</mark> <mark>Quarkus</mark>

  Also familiar with legacy stuff:   <mark>AS/400</mark> <mark> EDI/Integration </mark>

# Projects Section
# projects_title: objects

# Experience Section
experience_title: Experience

# Education Section
education_title: Educations and Specializations

# More Section
more_title: Skills
more_content: | # this will include new lines to allow paragraphs
  <pre>Language/Markup:     </pre> <mark>Java</mark> <mark>Typescript</mark> <mark>JavaScript</mark> <mark>Scala</mark> <mark>Kotlin</mark> <mark>Python</mark> <mark>Bash</mark> <mark>HTML</mark> <mark>S-CSS</mark> <mark>EDI X12</mark>

  <pre>Applications Servers:</pre> <mark>JBoss/Wildfly</mark> <mark>Weblogic</mark> <mark>Mule ESB</mark>

  <pre>Data/Messaging:      </pre> <mark>DB2/400</mark> <mark>Oracle</mark> <mark>Kafka</mark> <mark>MySQL</mark> <mark>PostreSQL</mark>

  <pre>System/Tools:        </pre> <mark>Linux</mark> <mark>IBM AS/400</mark> <mark>Docker</mark> <mark>Kubernetes</mark> <mark>GoCD</mark> <mark>Nexus</mark> <mark>SonarQube</mark> <mark>Git/Gitlab</mark> <mark>SVN</mark>

  <pre>API/Libraries:       </pre> <mark>Java EE</mark> <mark>JAX/RS</mark> <mark>Spring</mark> <mark>JPA/Hibernate</mark> <mark>Angular</mark> <mark>Arquillian</mark> <mark>Bean Validation</mark> 
      <mark>Vavr</mark> <mark>Bootstrap</mark> <mark>BIRT</mark> <mark>Apache Camel</mark> <mark>CDI</mark> <mark>Guava</mark> <mark>JMS</mark> <mark>JQuery</mark> 
      <mark>Mutlithreading</mark>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-minimal
